# Generated by Django 2.1.3 on 2018-12-04 09:21

import admission.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAdmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('date_deleted', models.DateField(blank=True, null=True)),
                ('admission_date', models.DateTimeField(auto_now_add=True)),
                ('batch', models.IntegerField()),
                ('description', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to=admission.models.scramble_uploaded_filename, verbose_name='Uploaded image')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
