# Generated by Django 2.0.7 on 2018-09-04 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0002_auto_20180904_0709'),
        ('main', '0002_auto_20180904_0709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('date_deleted', models.DateField(null=True)),
                ('type', models.IntegerField(choices=[('FATHER', 1), ('MOTHER', 2), ('LOCAL', 3)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GuardianStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('date_deleted', models.DateField(null=True)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guardain.Guardian')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
