# Generated by Django 2.0.7 on 2018-09-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardian',
            name='date_deleted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guardianstudent',
            name='date_deleted',
            field=models.DateField(blank=True, null=True),
        ),
    ]
