# Generated by Django 2.0.7 on 2018-09-04 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('date_deleted', models.DateField(null=True)),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('province', models.CharField(max_length=120)),
                ('district', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('zip_code', models.IntegerField()),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('date_deleted', models.DateField(null=True)),
                ('blood_group', models.CharField(max_length=120)),
                ('nationality', models.CharField(max_length=120)),
                ('mother_tongue', models.CharField(max_length=120)),
                ('religion', models.IntegerField(choices=[('HINDU', 1), ('MUSLIM', 2)])),
                ('citizenship_no', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('date_deleted', models.DateField(null=True)),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('type', models.IntegerField(choices=[('PHONE', 1), ('LANDLINE', 2), ('CDMA', 3)])),
                ('number', models.IntegerField()),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('date_deleted', models.DateField(null=True)),
                ('type', models.IntegerField(choices=[('ADMINISTRATOR', 1), ('TEACHER', 2), ('STUDENT', 3), ('GUEST', 4), ('ACCOUNTANT', 5), ('LIBRARIAN', 6)])),
                ('gender', models.IntegerField(choices=[('MALE', 1), ('FEMALE', 2), ('OTHERS', 3)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='detail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User'),
        ),
    ]
