# Generated by Django 2.1.3 on 2018-12-04 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('accountant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpayments',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
        migrations.AddField(
            model_name='payments',
            name='paid_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payments',
            name='paid_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
        migrations.AddField(
            model_name='payments',
            name='paid_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountant.Accountant'),
        ),
        migrations.AddField(
            model_name='payment_posting_reference',
            name='payment_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountant.Payments'),
        ),
        migrations.AddField(
            model_name='ledger',
            name='payment_posting_reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountant.Payment_posting_reference'),
        ),
        migrations.AddField(
            model_name='fees_due',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
        migrations.AddField(
            model_name='accountant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
