# Generated by Django 2.1.4 on 2018-12-28 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licence_no', models.CharField(max_length=20)),
                ('licence_valid_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20)),
                ('route', models.CharField(max_length=30)),
                ('start_location', models.CharField(max_length=30)),
                ('end_location', models.CharField(max_length=30)),
                ('no_of_seats', models.IntegerField()),
                ('max_allowed', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('stop_time', models.TimeField()),
                ('insurance_renew_date', models.DateField()),
                ('contact_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
