# Generated by Django 2.1.4 on 2019-01-02 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Section', '0002_auto_20181204_0921'),
        ('student', '0001_initial'),
        ('Class', '0001_initial'),
        ('course', '0007_classteacherallocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('date_deleted', models.DateField(blank=True, null=True)),
                ('name', models.CharField(max_length=30)),
                ('current_address', models.CharField(max_length=50)),
                ('permanent_address', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('license_no', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('date_deleted', models.DateField(blank=True, null=True)),
                ('start_location', models.CharField(max_length=30)),
                ('stop_location', models.CharField(max_length=30)),
                ('start_time', models.TimeField()),
                ('fee_amount', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('date_deleted', models.DateField(blank=True, null=True)),
                ('vehicle_no', models.CharField(max_length=20, unique=True)),
                ('no_of_seats', models.IntegerField()),
                ('max_allowed', models.IntegerField()),
                ('insurance_renew_date', models.DateField()),
                ('contact_person', models.CharField(max_length=40)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.BusStaff')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransportAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('date_deleted', models.DateField(blank=True, null=True)),
                ('_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Class.Class')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.Route')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Section.Section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='route',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.Transport'),
        ),
    ]
