# Generated by Django 2.1.4 on 2018-12-28 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transport',
            old_name='vehicle_number',
            new_name='vehicle_no',
        ),
    ]
