# Generated by Django 2.1.4 on 2018-12-28 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('course', '0006_assignsubject_electivesubject_subjectallocation'),
        ('Section', '0002_auto_20181204_0921'),
        ('Class', '0001_initial'),
        ('transport', '0002_auto_20181228_0730'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('date_deleted', models.DateField(blank=True, null=True)),
                ('start_location', models.CharField(max_length=30)),
                ('stop_location', models.CharField(max_length=30)),
                ('start_time', models.TimeField()),
                ('fee_amount', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransportAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('date_deleted', models.DateField(blank=True, null=True)),
                ('_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Class.Class')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.Route')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Section.Section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='busstaff',
            old_name='licence_valid_date',
            new_name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='busstaff',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='end_location',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='start_location',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='stop_time',
        ),
        migrations.AddField(
            model_name='busstaff',
            name='current_address',
            field=models.CharField(default='sdsa', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='busstaff',
            name='date_created',
            field=models.DateField(auto_now_add=True, default='2018-12-27'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='busstaff',
            name='date_deleted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='busstaff',
            name='date_updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='busstaff',
            name='name',
            field=models.CharField(default='dsaa', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='busstaff',
            name='permanent_address',
            field=models.CharField(default='sadas', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='busstaff',
            name='phone_number',
            field=models.CharField(default='15326556', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transport',
            name='date_created',
            field=models.DateField(auto_now_add=True, default='2018-12-27'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transport',
            name='date_deleted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='date_updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='driver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='transport.BusStaff'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transport',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.Route'),
        ),
    ]
