# Generated by Django 2.1.4 on 2018-12-28 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_auto_20181228_1026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busstaff',
            old_name='licence_no',
            new_name='license_no',
        ),
    ]
