# Generated by Django 2.1.4 on 2018-12-30 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_auto_20181228_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transport',
            name='route',
        ),
    ]
