# Generated by Django 2.1.4 on 2018-12-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_remove_transport_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='contact_person',
            field=models.CharField(max_length=40),
        ),
    ]
