# Generated by Django 2.1.4 on 2018-12-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0006_auto_20181230_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='vehicle_no',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
