# Generated by Django 2.1.3 on 2018-12-04 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Section', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('date_deleted', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('priority', models.CharField(max_length=120)),
                ('status', models.IntegerField(choices=[('SUBMITTED', 1), ('PENDING', 2)])),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=120)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('date_deleted', models.DateField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[('SUBMITTED', 1), ('PENDING', 2)])),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.Assignment')),
                ('section_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Section.SectionStudent')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
